title: Dirk Steynberg
description: Data Engineering, Technical Leadership, and Specialist Consulting
baseurl: ""
url: "https://bytemedirk.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author information
author:
  name: Dirk Steynberg
  email: bytemedirk@proton.me
  bio: "Data Engineering, Technical Leadership, and Specialist Consulting"
  location: South Africa
  linkedin: bytemedirk

# Site settings
permalink: /:title/
show_excerpts: true
header_pages:
  - about.md
  - projects.md
  - contact.md
